name: Build Node binaries for macOS

on:
  workflow_dispatch:
  workflow_call:

jobs:
  macos-x64:
    runs-on: macos-15-intel

    strategy:
      fail-fast: false
      matrix:
        target-node: [24]

    steps:
      - uses: actions/checkout@v4

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: yarn install --ignore-engines

      # add missing distutils package to python 3.12
      - name: Install distutils
        run: |
          pip install setuptools

      # Remove unneeded stuff to free up build space (from Node https://github.com/nodejs/build/issues/3878)
      - name: Cleanup before build
        run: |
          sudo rm -rf /Users/runner/Library/Android/sdk
          sudo rm -rf /Users/runner/Library/Developer/CoreSimulator/Caches
          # Additional cleanup for more space
          sudo rm -rf /Users/runner/.dotnet
          sudo rm -rf /Users/runner/Library/Caches/Homebrew/*
          echo "::group::Free space after cleanup"
          df -h
          echo "::endgroup::"

      # Show system info for debugging
      - name: System information
        run: |
          echo "CPU info:"
          sysctl -n machdep.cpu.brand_string
          sysctl -n hw.ncpu
          sysctl -n hw.physicalcpu
          sysctl -n hw.logicalcpu
          echo "Memory info:"
          sysctl -n hw.memsize | awk '{print $0/1024/1024/1024 " GB"}'

      - name: Build Node.js binary
        run: yarn start --node-range node${{ matrix.target-node }} --arch x64 --output dist
        env:
          MAKE_JOB_COUNT: 4 # Match CPU count for Intel runners (4 CPUs)
          CC_host: clang
          CXX_host: clang++
          CC: clang
          CXX: clang++
          GYP_DEFINES: "mac_deployment_target=13.0"

      - name: Check if binary is compiled, skip if download only
        id: check_file
        run: |
          ls -l dist
          (test -f dist/*.sha256sum && echo "EXISTS=true" >> $GITHUB_OUTPUT) || echo "EXISTS=false" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v4
        if: steps.check_file.outputs.EXISTS == 'true'
        with:
          name: node${{ matrix.target-node }}-macos-x64
          path: dist/*

  macos-arm64:
    runs-on: macos-14 # macos-14 is arm64: https://github.com/actions/runner-images#available-images

    strategy:
      fail-fast: false
      matrix:
        target-node: [20, 22, 24]

    steps:
      - uses: actions/checkout@v4

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Check arch is arm64
        run: |
          if [[ $(uname -m) != "arm64" ]]; then
            echo "This job should run on arm64 architecture"
            exit 1
          fi

      - run: yarn install --ignore-engines

      # add missing distutils package to python 3.12
      - name: Install distutils
        run: brew install python-setuptools

      # Remove unneeded stuff to free up build space (from Node https://github.com/nodejs/build/issues/3878)
      - name: Cleanup before build
        run: |
          sudo rm -rf /Users/runner/Library/Android/sdk
          sudo rm -rf /Users/runner/Library/Developer/CoreSimulator/Caches
          echo "::group::Free space after cleanup"
          df -h
          echo "::endgroup::"

      - run: yarn start --node-range node${{ matrix.target-node }} --arch arm64 --output dist
        env:
          MAKE_JOB_COUNT: 2 # prevent to run out of memory

      - name: Check if binary is compiled
        id: check_file
        run: |
          ls -l dist
          (test -f dist/*.sha256sum && echo "EXISTS=true" >> $GITHUB_OUTPUT) || echo "EXISTS=false" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v4
        if: steps.check_file.outputs.EXISTS == 'true'
        with:
          name: node${{ matrix.target-node }}-macos-arm64
          path: dist/*
